import {
  collection,
  doc,
  getDoc,
  getDocs,
  setDoc,
  updateDoc,
  query,
  where,
  serverTimestamp,
} from 'firebase/firestore';
import { db } from '../firebase/config';
import { uploadFile } from './storageService';
import { loadLocalSubmissions, saveLocalSubmission, getLocalSubmission } from './mbwLocalStore';
import { recordSubmissionEvent } from './submissionEventService';

export { loadLocalSubmissions };

export const MBW_TASKS = 'mbw_tasks';
export const MBW_SUBMISSIONS = 'mbw_submissions';

export const TASK_TYPES = {
  WATCH_ONLY: 'watch_only',
  TEXT: 'text',
  LINK: 'link',
  EDITABLE_TEMPLATE: 'editable_template',
  FILE_UPLOAD: 'file_upload',
  VIDEO_RECORD: 'video_record',
  RECURRING_POST: 'recurring_post',
  CHECKLIST: 'checklist',
};

export const SUBMISSION_STATUS = {
  LOCKED: 'locked',
  UNLOCKED: 'unlocked',
  SUBMITTED: 'submitted',
  UNDER_REVIEW: 'under_review',
  COMPLETED: 'completed',
};

/** Instructor review workflow — off for now; set true when admin review is re-enabled. */
export const MBW_REVIEW_ENABLED = false;

/** Firebase Storage uploads for MBW resume / video tasks. Off by default until bucket + rules are live. */
export const MBW_STORAGE_ENABLED = import.meta.env.VITE_MBW_STORAGE_ENABLED === 'true';

export function taskNeedsReview(task) {
  return MBW_REVIEW_ENABLED && !!task?.reviewRequired;
}

/** Pre-session task definitions (static — admin can override unlockDate in Firestore later). */
export const PRE_SESSION_TASKS = [
  {
    id: 'mbw-orientation',
    order: 0,
    phase: 'pre-preparation',
    week: 'Orientation',
    title: 'Orientation Session (by Rajesh)',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the orientation session to begin your MBW journey.',
  },
  {
    id: 'mbw-principles',
    order: 1,
    phase: 'pre-preparation',
    week: 'Wk1-12',
    title: '27 Principles Video',
    type: TASK_TYPES.TEXT,
    requiresWatch: true,
    videoUrl: 'https://www.youtube.com/watch?v=uo9xA5xiRWY',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the video, then submit 3 key learnings.',
    placeholder: 'Enter your 3 key learnings…',
  },
  {
    id: 'mbw-csuite',
    order: 2,
    phase: 'pre-preparation',
    week: 'Wk1-11',
    title: 'C-Suite Talk — Topic Finalization',
    type: TASK_TYPES.TEXT,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: true,
    description: 'Watch the session and submit your chosen talk topic for review.',
    placeholder: 'Your chosen C-Suite talk topic…',
  },
  {
    id: 'mbw-errc',
    order: 3,
    phase: 'pre-preparation',
    week: 'Wk1-10',
    title: 'ERRC Framework',
    type: TASK_TYPES.EDITABLE_TEMPLATE,
    requiresWatch: true,
    videoUrl: 'https://d3jv3ztk062m9h.cloudfront.net/videos/ERRC%20edited/output/ERRC%20edited.m3u8',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the ERRC video, then fill your activity grid (editable anytime).',
  },
  {
    id: 'mbw-linkedin-profile',
    order: 4,
    phase: 'pre-preparation',
    week: 'Wk1-9',
    title: 'LinkedIn Profile Update',
    type: TASK_TYPES.LINK,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Update your LinkedIn profile, then paste your profile URL here.',
    linkLabel: 'LinkedIn profile URL',
  },
  {
    id: 'mbw-linkedin-connects',
    order: 5,
    phase: 'pre-preparation',
    week: 'Wk1-8',
    title: 'LinkedIn Connects (Networking)',
    type: TASK_TYPES.RECURRING_POST,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Post on LinkedIn weekly and paste your post link. Builds your leadership brand.',
    postsPerWeek: 1,
  },
  {
    id: 'mbw-objectives',
    order: 6,
    phase: 'pre-preparation',
    week: 'Wk1-7',
    title: 'Objectives (Bhag)',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Write your personal objectives — your Bhag.',
    placeholder: 'Your objectives…',
  },
  {
    id: 'mbw-resume',
    order: 7,
    phase: 'pre-preparation',
    week: 'Wk1-6',
    title: 'Resume Updation',
    type: TASK_TYPES.FILE_UPLOAD,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    optional: true,
    description: 'Watch the guidance video, then upload your updated resume when ready.',
    accept: '.pdf,.doc,.docx',
    uploadSubmitLabel: 'Submit resume',
    uploadKind: 'resume',
  },
  {
    id: 'mbw-live-session',
    order: 8,
    phase: 'pre-preparation',
    week: 'Live',
    title: 'Live Session',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Attend / watch the live session recording.',
  },
  {
    id: 'mbw-mirror',
    order: 9,
    phase: 'pre-preparation',
    week: 'Wk1-5',
    title: 'Mirror Practice',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Record your mirror practice in the LMS or upload a video file.',
  },
  {
    id: 'mbw-lep',
    order: 10,
    phase: 'pre-preparation',
    week: 'LEP',
    title: 'LEP Practices',
    type: TASK_TYPES.CHECKLIST,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Complete each practice and tick it off — your progress is saved automatically.',
    checklistItems: ['Mirror work', 'A game', 'Powerful request', 'Gratitude'],
  },
  {
    id: 'mbw-networking-continued',
    order: 11,
    phase: 'pre-preparation',
    week: 'Networking',
    title: 'Networking Continued',
    type: TASK_TYPES.RECURRING_POST,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Continue networking — submit 2 LinkedIn post links this week.',
    postsPerWeek: 2,
    continuesTaskId: 'mbw-linkedin-connects',
  },
];

export const Q1_TASKS = [
  {
    id: 'q1-csuite-resume',
    order: 100,
    phase: 'quarter-1',
    week: 'Wk1',
    title: 'C-Suite Resume',
    type: TASK_TYPES.FILE_UPLOAD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Upload your updated C-Suite Resume.',
    accept: '.pdf,.doc,.docx',
    uploadSubmitLabel: 'Submit resume',
    uploadKind: 'resume',
  },
  {
    id: 'q1-linkedin-update',
    order: 101,
    phase: 'quarter-1',
    week: 'Wk2',
    title: 'LinkedIn Profile — C-Suite Update',
    type: TASK_TYPES.LINK,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Update your LinkedIn About section with your 50-word introduction, key accomplishment stories, specialization, and future vision. Share your updated profile link.',
    linkLabel: 'Updated LinkedIn profile URL',
  },
  {
    id: 'q1-session1',
    order: 102,
    phase: 'quarter-1',
    week: 'Session 1',
    title: 'Impact Champions: LinkedIn Profile & Post',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Attend / watch the Impact Champions session on LinkedIn Profile and Post.',
  },
  {
    id: 'q1-linkedin-posts',
    order: 103,
    phase: 'quarter-1',
    week: 'Wk3',
    title: 'LinkedIn Posts (×2)',
    type: TASK_TYPES.RECURRING_POST,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Write 2 powerful LinkedIn posts this week and submit both links.',
    postsPerWeek: 2,
  },
  {
    id: 'q1-csuite-story',
    order: 104,
    phase: 'quarter-1',
    week: 'Wk4',
    title: 'C-Suite Story',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Share 3 key stories of accomplishments in the WA group for review. Write them here.',
    placeholder: 'Story 1:\n\nStory 2:\n\nStory 3:',
  },
  {
    id: 'q1-session2',
    order: 105,
    phase: 'quarter-1',
    week: 'Session 2',
    title: 'Impact Champions: C-Suite Story Video',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on C-Suite Story Video.',
  },
  {
    id: 'q1-story-video',
    order: 106,
    phase: 'quarter-1',
    week: 'Wk5',
    title: 'C-Suite Story Video',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Record a short video sharing one of your accomplishment stories and share it in the group.',
  },
  {
    id: 'q1-bell-curve',
    order: 107,
    phase: 'quarter-1',
    week: 'Wk6',
    title: 'Your Position in the Bell Curve',
    type: TASK_TYPES.FILE_UPLOAD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Complete the Bell Curve Position worksheet using the template below, then upload it.',
    accept: '.pdf,.doc,.docx',
    uploadSubmitLabel: 'Upload worksheet',
  },
  {
    id: 'q1-suvarna-session',
    order: 108,
    phase: 'quarter-1',
    week: 'Session (Suvarna)',
    title: 'Strengthening Your Strengths (by Suvarna)',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Attend / watch the session with Suvarna on Strengthening Your Strengths.',
  },
  {
    id: 'q1-business-language',
    order: 109,
    phase: 'quarter-1',
    week: 'Wk7',
    title: 'Business Language',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Record a video answering 3 leadership questions as a C-Suite Leader using business language.',
  },
  {
    id: 'q1-milestone-table',
    order: 110,
    phase: 'quarter-1',
    week: 'Wk8',
    title: 'Milestone Table (Delta 2)',
    type: TASK_TYPES.FILE_UPLOAD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Fill in your Milestone Table using the Delta Table template, then upload your file.',
    accept: '.pdf,.doc,.docx,.pptx',
    uploadSubmitLabel: 'Upload milestone table',
  },
  {
    id: 'q1-session3',
    order: 111,
    phase: 'quarter-1',
    week: 'Session 3',
    title: 'Impact Champion: Video CV & C-Suite Application',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champion session on Video CV and applying for C-Suite roles.',
  },
  {
    id: 'q1-video-cv',
    order: 112,
    phase: 'quarter-1',
    week: 'Wk9',
    title: 'Video CV',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Record and share your Video CV.',
  },
  {
    id: 'q1-apply-csuite',
    order: 113,
    phase: 'quarter-1',
    week: 'Wk10',
    title: 'Apply for 1 C-Suite Job',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Apply for at least one C-Suite role and update your status here.',
    placeholder: 'Job title & company I applied to, and current status…',
  },
  {
    id: 'q1-session4',
    order: 114,
    phase: 'quarter-1',
    week: 'Session 4',
    title: 'Impact Champions: Revisit Super Power',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on revisiting your Super Power.',
  },
  {
    id: 'q1-super-power-table',
    order: 115,
    phase: 'quarter-1',
    week: 'Wk11',
    title: 'Super Power Table',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Create your Super Power Table and share one action you will take around it.',
    placeholder: 'My super powers:\n\nAction I will take:',
  },
  {
    id: 'q1-progress-report',
    order: 116,
    phase: 'quarter-1',
    week: 'Wk12',
    title: 'Q1 Progress Report',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Share your progress report covering: C-Suite CV & LinkedIn, C-Suite Story, your position in your growth journey, Milestone Table, and Business Language.',
    placeholder: '1. C-Suite CV & LinkedIn:\n2. C-Suite Story:\n3. Growth journey position:\n4. Milestone Table:\n5. Business Language:',
  },
];

export const Q2_TASKS = [
  {
    id: 'q2-differentiation',
    order: 200,
    phase: 'quarter-2',
    week: 'Wk13',
    title: 'Differentiation Statement',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Assess the situation, identify your enemy, and record a 30-second video of one statement that differentiates you against your enemy.',
  },
  {
    id: 'q2-apply-connects',
    order: 201,
    phase: 'quarter-2',
    week: 'Wk14',
    title: 'Resume Review + Apply + 3 Connects',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Get your resume reviewed in your group, apply for C-Suite positions, and reach out to 3 business owners/C-Suite leaders. Share update on connects/job application status.',
    placeholder: 'Resume review feedback:\n\nJobs applied to:\n\n3 connects made:',
  },
  {
    id: 'q2-session5',
    order: 202,
    phase: 'quarter-2',
    week: 'Session 5',
    title: 'Impact Champions: Pitch Video',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Pitch Video.',
  },
  {
    id: 'q2-pitch-video',
    order: 203,
    phase: 'quarter-2',
    week: 'Wk15',
    title: 'Pitch Video (1.5 mins)',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Define your problem statement and record a 1.5-minute pitch video.',
  },
  {
    id: 'q2-buddy-rejection',
    order: 204,
    phase: 'quarter-2',
    week: 'Wk16',
    title: 'Buddy Rejection Practice',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Practice with your buddy — you pitch and your buddy rejects. Practice your response and try to convince them. Share your key learnings.',
    placeholder: 'Key learnings from the buddy rejection practice…',
  },
  {
    id: 'q2-session6',
    order: 205,
    phase: 'quarter-2',
    week: 'Session 6',
    title: 'Impact Champions: Strategy Revision',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Strategy Revision.',
  },
  {
    id: 'q2-strategy-draft',
    order: 206,
    phase: 'quarter-2',
    week: 'Wk17',
    title: 'Strategy — First Draft',
    type: TASK_TYPES.FILE_UPLOAD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Complete the strategy document template for one business outcome, then upload it.',
    accept: '.pdf,.doc,.docx',
    uploadSubmitLabel: 'Upload strategy draft',
  },
  {
    id: 'q2-super-powers-video',
    order: 207,
    phase: 'quarter-2',
    week: 'Wk18',
    title: 'Super Powers in Action',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Revisit your super powers and use them this week. Record a short video on which super powers you used.',
  },
  {
    id: 'q2-suvarna-session',
    order: 208,
    phase: 'quarter-2',
    week: 'Session (Suvarna)',
    title: 'Deception/Drama Revision (by Suvarna)',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the session with Suvarna on Deception/Drama Revision.',
  },
  {
    id: 'q2-drama-practice',
    order: 209,
    phase: 'quarter-2',
    week: 'Wk19',
    title: 'Drama Practice — Live',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Practice Drama live. Share the drama you did this week and the experience you had in 3 lines.',
    placeholder: 'The drama I practiced:\n\nMy experience (3 lines):',
  },
  {
    id: 'q2-errc-delegation',
    order: 210,
    phase: 'quarter-2',
    week: 'Wk20',
    title: 'ERRC Revisit — Delegation',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Revisit your ERRC using upward/sideways delegation. Share the amount of time saved and new activities started.',
    placeholder: 'Time saved:\n\nNew activities started:',
  },
  {
    id: 'q2-session7',
    order: 211,
    phase: 'quarter-2',
    week: 'Session 7',
    title: 'Impact Champions: Networking',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Networking (LinkedIn Profile & Connect).',
  },
  {
    id: 'q2-linkedin-daily',
    order: 212,
    phase: 'quarter-2',
    week: 'Wk21',
    title: 'LinkedIn Post Challenge (Daily)',
    type: TASK_TYPES.RECURRING_POST,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: '1 LinkedIn post daily for this week. Submit all 7 post links.',
    postsPerWeek: 7,
  },
  {
    id: 'q2-delta2-revisit',
    order: 213,
    phase: 'quarter-2',
    week: 'Wk22',
    title: 'Delta 2 + Milestone Table',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Revisit your Delta 2 and Milestone Table. Share your Kaizen for this week.',
    placeholder: 'Delta 2 update:\n\nMilestone Table update:\n\nKaizen (improvement) for this week:',
  },
  {
    id: 'q2-session8',
    order: 214,
    phase: 'quarter-2',
    week: 'Session 8',
    title: 'Impact Champions: C-Suite Talk Preparation',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Preparation for C-Suite Talk.',
  },
  {
    id: 'q2-csuite-talk-practice',
    order: 215,
    phase: 'quarter-2',
    week: 'Wk23',
    title: 'C-Suite Talk Practice (Buddy)',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Practice your C-Suite talk with your buddy. Record a short video of your topic and preparation steps.',
  },
  {
    id: 'q2-progress-report',
    order: 216,
    phase: 'quarter-2',
    week: 'Wk24',
    title: 'Q2 Progress Report',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Share your Q2 progress report.',
    placeholder: 'Q2 progress report:',
  },
];

export const Q3_TASKS = [
  {
    id: 'q3-interview-mock',
    order: 300,
    phase: 'quarter-3',
    week: 'Wk25',
    title: 'C-Suite Interview Mock Video',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Record a video answering 3 C-Suite interview questions based on a JD specific to your profile.',
  },
  {
    id: 'q3-terrain',
    order: 301,
    phase: 'quarter-3',
    week: 'Wk26',
    title: 'Terrain Assessment',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Assess your terrain — identify your enemy, energy center, and business goal relevant to you. Share 2 key actions you will take this week.',
    placeholder: 'Enemy:\nEnergy center:\nBusiness goal:\n\n2 key actions:',
  },
  {
    id: 'q3-session9',
    order: 302,
    phase: 'quarter-3',
    week: 'Session 9',
    title: 'Impact Champions: Business Perspective',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Business Perspective — aligning situations, proposals, and stories to business parameters.',
  },
  {
    id: 'q3-business-language-video',
    order: 303,
    phase: 'quarter-3',
    week: 'Wk27',
    title: 'Business Language Video (2 mins)',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Record a 2-minute video sharing a new idea, proposal, or introduction using business language.',
  },
  {
    id: 'q3-linkedin-video',
    order: 304,
    phase: 'quarter-3',
    week: 'Wk28',
    title: 'LinkedIn Video Challenge',
    type: TASK_TYPES.LINK,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Make at least one video and share it on LinkedIn. Paste the LinkedIn post link here.',
    linkLabel: 'LinkedIn video post URL',
  },
  {
    id: 'q3-session10',
    order: 305,
    phase: 'quarter-3',
    week: 'Session 10',
    title: 'Impact Champions: Energy Centers',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Revision of Energy Centers.',
  },
  {
    id: 'q3-energy-centers',
    order: 306,
    phase: 'quarter-3',
    week: 'Wk29',
    title: 'Energy Centers Action Plan',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Identify key energy centers and create your action plan to collaborate with them.',
    placeholder: 'Key energy centers:\n\nAction plan to collaborate:',
  },
  {
    id: 'q3-book-video',
    order: 307,
    phase: 'quarter-3',
    week: 'Wk30',
    title: 'Book Learning Video',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Record a short video explaining a learning from any book as if you are the author.',
  },
  {
    id: 'q3-suvarna-session',
    order: 308,
    phase: 'quarter-3',
    week: 'Session (Suvarna)',
    title: 'Influencing Tactics (by Suvarna)',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the session with Suvarna on Revision of Influencing Tactics.',
  },
  {
    id: 'q3-role-play',
    order: 309,
    phase: 'quarter-3',
    week: 'Wk31',
    title: 'Role Play with Buddy',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Practice a role play with your buddy — suggest an idea and convince your boss/customer using influencing tactics. Share your experience.',
    placeholder: 'My role play scenario:\n\nInfluencing tactics used:\n\nExperience:',
  },
  {
    id: 'q3-signalling-video',
    order: 310,
    phase: 'quarter-3',
    week: 'Wk32',
    title: 'Direct & Indirect Signalling',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Practice direct and indirect signalling. Record a video explaining one scenario and your way of indirect signalling in that scenario.',
  },
  {
    id: 'q3-session11',
    order: 311,
    phase: 'quarter-3',
    week: 'Session 11',
    title: 'Impact Champions: Offence & Defence',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Revision of Offence and Defence Game.',
  },
  {
    id: 'q3-game-plan',
    order: 312,
    phase: 'quarter-3',
    week: 'Wk33',
    title: 'Game Plan',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Make your game plan based on your current situation.',
    placeholder: 'My current situation:\n\nGame plan:',
  },
  {
    id: 'q3-delta2-revisit',
    order: 313,
    phase: 'quarter-3',
    week: 'Wk34',
    title: 'Delta 2 + Milestone Table Revisit',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Revisit your Delta 2 and Milestone Table. Share your progress so far and commitment for the future.',
    placeholder: 'Progress so far:\n\nCommitment for the future:',
  },
  {
    id: 'q3-session12',
    order: 314,
    phase: 'quarter-3',
    week: 'Session 12',
    title: 'Impact Champions: C-Suite Mock Interview',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on C-Suite Mock Interview.',
  },
  {
    id: 'q3-csuite-talk-prep',
    order: 315,
    phase: 'quarter-3',
    week: 'Wk35',
    title: 'C-Suite Talk Preparation',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Prepare your C-Suite Talk. Share the topic and script.',
    placeholder: 'Topic:\n\nScript:',
  },
  {
    id: 'q3-progress-report',
    order: 316,
    phase: 'quarter-3',
    week: 'Wk36',
    title: 'Q3 Progress Report',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Share your Q3 progress report.',
    placeholder: 'Q3 progress report:',
  },
];

export const Q4_TASKS = [
  {
    id: 'q4-linkedin-reposition',
    order: 400,
    phase: 'quarter-4',
    week: 'Wk37',
    title: 'LinkedIn Repositioning (×2 Posts)',
    type: TASK_TYPES.RECURRING_POST,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Update your LinkedIn profile and post topics as per your repositioning. Share 2 posts from a new angle this week.',
    postsPerWeek: 2,
  },
  {
    id: 'q4-errc-revision',
    order: 401,
    phase: 'quarter-4',
    week: 'Wk38',
    title: 'ERRC Revision',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Revise your ERRC. Share time saved and new things created.',
    placeholder: 'Time saved:\n\nNew things created:',
  },
  {
    id: 'q4-session13',
    order: 402,
    phase: 'quarter-4',
    week: 'Session 13',
    title: 'Impact Champions: Bell Curve Revision',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Revision of Bell Curve.',
  },
  {
    id: 'q4-bell-curve-game-plan',
    order: 403,
    phase: 'quarter-4',
    week: 'Wk39',
    title: 'Bell Curve + C-Suite Game Plan',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Revisit your position in the bell curve and create your C-Suite game plan. Share your position and game plan.',
    placeholder: 'My position in the bell curve:\n\nC-Suite game plan:',
  },
  {
    id: 'q4-projection-practice',
    order: 404,
    phase: 'quarter-4',
    week: 'Wk40',
    title: 'Projection Practice',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Take one success scenario and one failure scenario — practice projection in each. Share key takeaways.',
    placeholder: 'Success scenario projection:\n\nFailure scenario projection:\n\nKey takeaways:',
  },
  {
    id: 'q4-session14',
    order: 405,
    phase: 'quarter-4',
    week: 'Session 14',
    title: 'Impact Champions: Enemy-Based Strategy',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Revision of Enemy-Based Strategy.',
  },
  {
    id: 'q4-delta2-video',
    order: 406,
    phase: 'quarter-4',
    week: 'Wk41',
    title: 'Delta 2 Progress Video',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Review your Delta 2 Table progress so far. Record a short video updating your progress using business language.',
  },
  {
    id: 'q4-multi-view-strategy',
    order: 407,
    phase: 'quarter-4',
    week: 'Wk42',
    title: 'Multi-View Strategy',
    type: TASK_TYPES.FILE_UPLOAD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Create your multi-view strategy using the template below, then upload your document.',
    accept: '.pdf,.doc,.docx',
    uploadSubmitLabel: 'Upload strategy document',
  },
  {
    id: 'q4-suvarna-session',
    order: 408,
    phase: 'quarter-4',
    week: 'Session (Suvarna)',
    title: 'C-Suite Game Plan (by Suvarna)',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the session with Suvarna on C-Suite Game Plan.',
  },
  {
    id: 'q4-csuite-game-plan',
    order: 409,
    phase: 'quarter-4',
    week: 'Wk43',
    title: 'C-Suite Game Plan',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Create your C-Suite game plan for one scenario.',
    placeholder: 'Scenario:\n\nC-Suite game plan:',
  },
  {
    id: 'q4-challenges',
    order: 410,
    phase: 'quarter-4',
    week: 'Wk44',
    title: 'Challenges Assessment',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Assess the surroundings and make a list of challenges.',
    placeholder: 'List of challenges:',
  },
  {
    id: 'q4-session15',
    order: 411,
    phase: 'quarter-4',
    week: 'Session 15',
    title: 'Impact Champions: Drama & Deception',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Drama/Deception.',
  },
  {
    id: 'q4-drama-video',
    order: 412,
    phase: 'quarter-4',
    week: 'Wk45',
    title: 'Drama Situations Practice',
    type: TASK_TYPES.VIDEO_RECORD,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Practice drama — take 3 situations and practice in mirror how to do drama. Record a video of at least one drama situation.',
  },
  {
    id: 'q4-rejection-practice',
    order: 413,
    phase: 'quarter-4',
    week: 'Wk46',
    title: 'Pitch Rejection Scenario (Buddy)',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Practice the rejection scenario for your pitch with your buddy. Share your experience.',
    placeholder: 'My experience from the rejection practice:',
  },
  {
    id: 'q4-session16',
    order: 414,
    phase: 'quarter-4',
    week: 'Session 16',
    title: 'Impact Champions: ERRC Revision',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Watch the Impact Champions session on Revision of ERRC.',
  },
  {
    id: 'q4-final-errc',
    order: 415,
    phase: 'quarter-4',
    week: 'Wk47',
    title: 'Final ERRC Revision',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Revise your ERRC. Share time saved and new things created.',
    placeholder: 'Time saved:\n\nNew things created:',
  },
  {
    id: 'q4-apply-csuite',
    order: 416,
    phase: 'quarter-4',
    week: 'Wk48',
    title: 'Apply for C-Suite Position',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Apply for a C-Suite position and share your experience.',
    placeholder: 'Position applied for:\n\nMy experience:',
  },
];

export const GRADUATION_TASKS = [
  {
    id: 'grad-prep-1',
    order: 500,
    phase: 'graduation',
    week: 'Wk49',
    title: 'Graduation Preparation — Week 1',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Begin preparing for graduation. Document your key milestones and achievements from the program.',
    placeholder: 'Key milestones achieved:\n\nPreparation notes:',
  },
  {
    id: 'grad-prep-2',
    order: 501,
    phase: 'graduation',
    week: 'Wk50',
    title: 'Graduation Preparation — Week 2',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Continue preparing for graduation. Refine your C-Suite story and talk.',
    placeholder: 'C-Suite story refinement:\n\nTalk preparation:',
  },
  {
    id: 'grad-prep-3',
    order: 502,
    phase: 'graduation',
    week: 'Wk51',
    title: 'Graduation Preparation — Week 3',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Final preparation for graduation. Review all deliverables and get ready to present.',
    placeholder: 'Final preparation notes:',
  },
  {
    id: 'grad-prep-4',
    order: 503,
    phase: 'graduation',
    week: 'Wk52',
    title: 'Graduation Preparation — Week 4',
    type: TASK_TYPES.TEXT,
    requiresWatch: false,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Complete all final preparations for your graduation ceremony.',
    placeholder: 'Completion checklist and notes:',
  },
  {
    id: 'grad-ceremony',
    order: 504,
    phase: 'graduation',
    week: 'Graduation',
    title: 'Graduation Ceremony',
    type: TASK_TYPES.WATCH_ONLY,
    requiresWatch: true,
    videoUrl: '',
    unlockDate: null,
    reviewRequired: false,
    description: 'Attend your MBW Graduation Ceremony — celebrate the completion of your C-Suite journey!',
  },
];

export function submissionDocId(userId, taskId) {
  return `${userId}_${taskId}`;
}

export function currentWeekLabel(date = new Date()) {
  const start = new Date(date.getFullYear(), 0, 1);
  const week = Math.ceil(((date - start) / 86_400_000 + start.getDay() + 1) / 7);
  return `${date.getFullYear()}-W${String(week).padStart(2, '0')}`;
}

export function getStaticTasks() {
  return [
    ...PRE_SESSION_TASKS,
    ...Q1_TASKS,
    ...Q2_TASKS,
    ...Q3_TASKS,
    ...Q4_TASKS,
    ...GRADUATION_TASKS,
  ].sort((a, b) => a.order - b.order);
}

export async function fetchFirestoreTasks() {
  if (!db) return null;
  try {
    const snap = await getDocs(collection(db, MBW_TASKS));
    if (snap.empty) return null;
    const tasks = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
    return tasks.sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
  } catch {
    return null;
  }
}

export async function getTasks() {
  const remote = await fetchFirestoreTasks();
  return remote?.length ? remote : getStaticTasks();
}

export async function getSubmission(userId, taskId) {
  const subId = submissionDocId(userId, taskId);
  if (db) {
    try {
      const snap = await getDoc(doc(db, MBW_SUBMISSIONS, subId));
      if (snap.exists()) return { id: snap.id, ...snap.data() };
    } catch {
      /* fall through to local */
    }
  }
  return getLocalSubmission(userId, taskId);
}

export async function getUserSubmissions(userId) {
  const map = { ...loadLocalSubmissions(userId) };
  if (db) {
    try {
      const q = query(collection(db, MBW_SUBMISSIONS), where('userId', '==', userId));
      const snap = await getDocs(q);
      snap.docs.forEach((d) => {
        map[d.data().taskId] = { id: d.id, ...d.data() };
      });
    } catch {
      /* use local only */
    }
  }
  return map;
}

export async function getAllSubmissions() {
  if (!db) return Object.values(loadLocalSubmissions('all'));
  const snap = await getDocs(collection(db, MBW_SUBMISSIONS));
  return snap.docs.map((d) => ({ id: d.id, ...d.data() }));
}

export async function saveSubmission(userId, taskId, payload, { batchId = 'default' } = {}) {
  const subId = submissionDocId(userId, taskId);
  const data = {
    taskId,
    userId,
    batchId,
    updatedAt: serverTimestamp(),
    ...payload,
  };

  if (db) {
    try {
      const ref = doc(db, MBW_SUBMISSIONS, subId);
      const writeData = getLocalSubmission(userId, taskId)
        ? data
        : { ...data, createdAt: serverTimestamp() };
      // merge create/update in one call — updateDoc on a missing doc returns permission-denied.
      await setDoc(ref, writeData, { merge: true });
      const qualifying = [SUBMISSION_STATUS.SUBMITTED, SUBMISSION_STATUS.UNDER_REVIEW, SUBMISSION_STATUS.COMPLETED];
      if (qualifying.includes(payload.status)) {
        recordSubmissionEvent({
          learnerId: userId,
          courseId: batchId || 'mbw',
          problemId: taskId,
          isCorrect: true,
        }).catch(() => {});
      }
      return { id: subId, ...payload, taskId, userId, batchId };
    } catch (err) {
      console.warn('Firestore save failed, using localStorage', err?.code, err?.message || err);
    }
  }

  return saveLocalSubmission(userId, taskId, { ...payload, batchId });
}

export async function uploadMbwFile(userId, taskId, file, kind = 'file') {
  if (!MBW_STORAGE_ENABLED) {
    return {
      url: null,
      path: null,
      fileName: file.name,
      localFallback: true,
      size: file.size,
      type: file.type,
    };
  }

  try {
    const { url, path, fileName } = await uploadFile(file, `mbw/${userId}/${taskId}/${kind}`, {
      uploadedBy: userId,
      source: 'mbw',
      sourceId: `${userId}_${taskId}`,
      sourceLabel: `MBW ${kind} — ${taskId}`,
    });
    return { url, path, fileName };
  } catch (err) {
    console.warn('Storage upload failed', err);
    return {
      url: null,
      path: null,
      fileName: file.name,
      localFallback: true,
      size: file.size,
      type: file.type,
    };
  }
}

export async function reviewSubmission(subId, { approved, feedback, reviewerId }) {
  if (!db) throw new Error('Review requires Firestore');
  const status = approved ? SUBMISSION_STATUS.COMPLETED : SUBMISSION_STATUS.UNLOCKED;
  await updateDoc(doc(db, MBW_SUBMISSIONS, subId), {
    status,
    feedback: feedback || '',
    reviewedBy: reviewerId,
    reviewedAt: serverTimestamp(),
    completedAt: approved ? serverTimestamp() : null,
    updatedAt: serverTimestamp(),
  });
}

export async function updateTaskUnlockDate(taskId, unlockDate) {
  if (!db) throw new Error('Firestore required');
  await setDoc(
    doc(db, MBW_TASKS, taskId),
    { unlockDate, updatedAt: serverTimestamp() },
    { merge: true }
  );
}
